In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
%cd/content/drive/MyDrive/colab

/content/drive/MyDrive/colab


x[0,:,:,:]

x[:,0,:,：]

x[:,:,0,:]

x[:,:,：,0]

In [35]:
import numpy as np

a=np.array([[[[0,1,3],[4,5,6],[7,8,9]],
      [[10,11,12],[13,14,15],[16,17,18]],
      [[19,20,21],[22,23,24],[25,26,27]]],
     [[[28,29,30],[31,32,33],[34,35,36]],
      [[37,38,39],[40,41,42],[43,44,45]],
      [[46,47,48],[49,50,51],[52,53,54]]]])
b=a[0,:,:,:]
c=a[:,0,:,:]
d=a[:,:,0,:]
e=a[:,:,:,0]
print(b,'\n','\n',c,'\n','\n',d,'\n','\n',e)

[[[ 0  1  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 
 
 [[[ 0  1  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]] 
 
 [[[ 0  1  3]
  [10 11 12]
  [19 20 21]]

 [[28 29 30]
  [37 38 39]
  [46 47 48]]] 
 
 [[[ 0  4  7]
  [10 13 16]
  [19 22 25]]

 [[28 31 34]
  [37 40 43]
  [46 49 52]]]


In [34]:
import numpy as np

a=np.array([[[0,1,3],[4,5,6],[7,8,9]],
      [[10,11,12],[13,14,15],[16,17,18]],
      [[19,20,21],[22,23,24],[25,26,27]]])
b=a[:,:,0]
c=a[:,0,:]
d=a[0,:,:]
print(b,'\n','\n',c,'\n','\n',d)

[[ 0  4  7]
 [10 13 16]
 [19 22 25]] 
 
 [[ 0  1  3]
 [10 11 12]
 [19 20 21]] 
 
 [[0 1 3]
 [4 5 6]
 [7 8 9]]
